server:
  port: 17000
spring:
  application:
    name: mall-search
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - localhost:9200
logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: trace
